heat_template_version: 2014-10-16

description: >
  Example extra config for post-deployment

# Note extra parameters can be defined, then passed data via the
# environment parameter_defaults, without modifying the parent template
parameters:
  server:
    type: string

resources:

  ExtraPreConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: |
         #!/bin/bash
         # Enable lbaasv2 HA
         if `hostname | grep cont`
         then
         crudini --set /etc/neutron/neutron_lbaas.conf DEFAULT allow_automatic_lbaas_agent_failover true
         fi

         #yum update
         curl -o /etc/yum.repos.d/osp10.repo  http://192.168.90.254/repo/osp10.repo
         yum -y update

  ExtraPreDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      name: ExtraPreDeployment
      server:  {get_param: server}
      config: {get_resource: ExtraPreConfig}
      actions: ['CREATE'] # Only do this on CREATE

outputs:
  deploy_stdout:
    description: Deployment reference, used to trigger pre-deploy on changes 
    value: {get_attr: [ExtraPreDeployment, deploy_stdout]}
